# ConfigMap dónde se definen variables de entorno privadas y encodeadas en Base64
# See: https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 string: PasswordSecretRandom
  JWT_SECRET: UGFzc3dvcmRTZWNyZXRSYW5kb20=
